name: backend-ci-cd
on:
 push:
  branches: [main]

jobs:
 build:
  name: Build
  runs-on: ubuntu-latest
  env:
    DB_URL_COMMON: ${{ secrets.DB_URL_COMMON }}
    TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
    GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
    STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
    CLIENT_URL: ${{ secrets.CLIENT_URL }}
  steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: "19.x"

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get npm cache directory
      id: npm-cache-dir
      shell: bash
      run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

    - name: Install dependencies
      run: npm install --frozen-lockfile

    - name: Integration test
      run: npm test
    - name: Build
      run: npm run build
    